Add email invoice trigger
cobot/zapier pull request #88
Opened 2024-04-29 11:52 UTC by Jsnxyz

Added membership email to invoice trigger output 

Fixes #87

2024-04-30 10:34 UTC, langalex requested changes

2024-04-30 10:34 UTC, langalex commented on src/utils/api.ts
> +  const membershipPromises: Promise<InvoiceApiResponse>[] = [];
why do membership promises have an invoice type?

2024-04-30 10:34 UTC, langalex commented on src/types/api-responses.d.ts
> +  membership?: {
this should go into InvoiceOutput, not here. Since BaseInvoiceProperties goes into InvoiceApiResponse, we are now pretending the invoice api returns membership data as part of the invoice

2024-04-30 10:34 UTC, langalex commented on src/utils/api.ts
> +const loadMembershipEmailOnInvoice = async (
this works, but it makes it hard tp follow what is going on. see my comment on the invoice base properties types. please keep invoice and membership api responses separate until merging them into InvoiceOutput.

2024-04-30 10:34 UTC, langalex commented on src/utils/api.ts
> +  const api1MembershipUrl = `https://${subdomain}.cobot.me/api/memberships`;
this is not a membership url, since the id is missing. how about you just pass around the subdomain and build the url once you have the membership id. or you build the complete url here.

2024-05-06 07:30 UTC, langalex requested changes

2024-05-06 07:30 UTC, langalex commented on src/test/triggers/triggerInvoiceCreated.test.ts
> +          membershipId: "membership-1",
could just be called id since it's inside membership

2024-05-06 07:30 UTC, langalex commented on src/triggers/triggerInvoiceCreated.ts
> +    new URL(bundle.cleanedRequest.url).origin + "/api/memberships";
why is api1MembershipsUrl URL here and a string in line 75?

2024-05-06 07:30 UTC, langalex commented on src/utils/api.ts
> +export const loadMembershipEmailOnInvoice = async (
can you clean this up a bit? all (other) functions in this file return api responses. the conversion from api response to output happen in api-to-output.ts

2024-05-06 07:30 UTC, langalex commented on src/utils/api.ts
> +export const loadMembershipEmailOnInvoice = async (
```suggestion
export const getMembership = async (
```

2024-05-06 13:58 UTC, Jsnxyz commented on src/triggers/triggerInvoiceCreated.ts
> +    new URL(bundle.cleanedRequest.url).origin + "/api/memberships";
Its a string here too. I am just using GET /invoice url to construct memberships url

2024-05-06 14:46 UTC, merged